- name: create config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)

- name: create
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "CIpipelines/{{COMPONENT}}"
    url: http://172.31.2.167:8080
    user: admin
    password: "{{jenkins_password}}"