- name: create folder - {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.12.160:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"


- name: create multibranch pipeline jobs file
  ansible.builtin.include_tasks: m-branchpipeline.yml
  loop: "{{ CI_pipeline_jobs }}"

- name: create singlebranch pipeline jobs file
  ansible.builtin.include_tasks: s-branchpipeline.yml
  loop: "{{ sbranchpipeline_jobs}}"