#- name: Check if Job exists or not - {{item.dir}}/{{item.name}}
#  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.2.167:8080 -webSocket get-job {{item.dir}}/{{item.name}}
#  register: out
#  ignore_errors: yes

- name: create config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
#  when: out.rc == 3


- name: create job - {{item.dir}}/{{item.name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name }}"
    url: http://172.31.33.228:8080
    user: admin
    password: "{{jenkins_password}}"
#  when: out.rc == 3
